# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a10f681215badb45e33f47c33ee0b2c479b489a92612bb394f699a0b18040368eb7f034794542f5dfc3d7340f0c59f0b123dd6e384f37fc825cee89e1e85cc8c

test:
  secret_key_base: 2332c7963789e5bb21b9480bbe3943f056571c2f9bbcc4abfdf45090a4dd8ddc468e6e93987790f7dbd325eaae59773d598a6de110ed75acbf75714be5e2d034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
